### ISSUE TITLE
Minecraft 1.18.2 Crash

### ISSUE THREAD

**Issue by kalinzange** [plusls/xaero-map-addition#2]
Hi,

Windows 11 / Minecraft 1.18.2 
[crash-2022-06-01_01.01.47-client.txt](https://github.com/plusls/xaero-map-addition/files/8810083/crash-2022-06-01_01.01.47-client.txt)

I'm also using [Xaero's Minimap - Modded Support Resource Pack](https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-modded-support), this might be the issue that is causing the crash.

Cheers

**Comment by plusls** [comment]
try github action?

**Comment by kalinzange** [comment]
> try github action?

A potential solution has been determined:
	 - Replace mod 'MagicLib' (magiclib) 0.3.26 with version 0.5.5 or later.
Unmet dependency listing:
	 - Mod 'Xaero Map Addition' (xaero_map_addition) 0.2.2-beta+959d339 requires version 0.5.5 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.3.26!
	 - Mod 'MagicLib Compat' (magiclib-compat-mc1_14) 0.3.26 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'MagicLib Compat' (magiclib-compat-mc1_15) 0.3.26 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'MagicLib Compat' (magiclib-compat-mc1_16) 0.3.26 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'MagicLib Compat' (magiclib-compat-mc1_17) 0.3.26 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'MagicLib Compat' (magiclib-compat-mc1_19) 0.3.26 requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
[Magiclib Mod Latest Version is 0.3.26](https://www.curseforge.com/minecraft/mc-mods/magiclib/files/all)

**Comment by plusls** [comment]
https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.5.27

**Comment by kalinzange** [comment]
[crash-2022-06-01_12.07.21-client.txt](https://github.com/plusls/xaero-map-addition/files/8813487/crash-2022-06-01_12.07.21-client.txt)
It Still Crashed

**Comment by plusls** [comment]
I push a new commit, try it ?

**Comment by kalinzange** [comment]
Success - No Crashes This Time + Able to Create a World
