### ISSUE TITLE
Any planned update on 1.19.2?

### ISSUE THREAD

**Issue by Sawaumi** [plusls/xaero-map-addition#6]
A reliease date would be appreciated :)

**Comment by Hendrix-Shen** [comment]
See #5.
> 考虑到 GitHub Actions 构建文件需要登录账号，并且90天过期，将转移到 [Nyan-Work/xaero-map-addition](https://github.com/Nyan-Work/xaero-map-addition) 发布 prerelease。
> 
> Considering that GitHub Actions build artifacts require a login and expire in 90 days, they will be moved to the [Nyan-Work/xaero-map-addition](https://github.com/Nyan-Work/xaero-map-addition) release prerelease.
