### ISSUE TITLE
与钠0.4.9使用时崩溃

### ISSUE THREAD

**Issue by HhiPyrene** [plusls/xaero-map-addition#7]
[crash-2023-02-07_17.23.32-client.txt](https://github.com/plusls/xaero-map-addition/files/10674577/crash-2023-02-07_17.23.32-client.txt)

**Comment by Hendrix-Shen** [comment]
尝试 [0.2.61+ff7804a](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.5) 版本。

**Comment by HhiPyrene** [comment]
> 尝试 [0.2.61+ff7804a](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.5) 版本。

已修复。

**Comment by HhiPyrene** [comment]
> 尝试 [0.2.61+ff7804a](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.5) 版本。

[crash-2023-02-09_15.12.27-client.txt](https://github.com/plusls/xaero-map-addition/files/10694420/crash-2023-02-09_15.12.27-client.txt)
[latest.log](https://github.com/plusls/xaero-map-addition/files/10694422/latest.log)
无法打开路径点界面。

**Comment by Hendrix-Shen** [comment]
尝试 [0.2.66+ad96d92](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.6) 版本。

**Comment by HhiPyrene** [comment]
> 尝试 [0.2.66+ad96d92](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.6) 版本。

可正常工作。
